set_property IOSTANDARD LVCMOS18 [get_ports {Anode[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Anode[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Anode[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Anode[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Anode[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Anode[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Anode[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Anode[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {Display[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports Clk]
set_property IOSTANDARD LVCMOS18 [get_ports Reset] 

## Clock Signal
set_property PACKAGE_PIN E3 [get_ports Clk]

## Switches
set_property PACKAGE_PIN J15 [get_ports Reset]

## 7 Segement Display
set_property PACKAGE_PIN U13 [get_ports {Anode[7]}]
set_property PACKAGE_PIN K2 [get_ports {Anode[6]}]
set_property PACKAGE_PIN T14 [get_ports {Anode[5]}]
set_property PACKAGE_PIN P14 [get_ports {Anode[4]}]
set_property PACKAGE_PIN J14 [get_ports {Anode[3]}]
set_property PACKAGE_PIN T9 [get_ports {Anode[2]}]
set_property PACKAGE_PIN J18 [get_ports {Anode[1]}]
set_property PACKAGE_PIN J17 [get_ports {Anode[0]}]
set_property PACKAGE_PIN H15 [get_ports {Display[7]}]
set_property PACKAGE_PIN L18 [get_ports {Display[6]}]
set_property PACKAGE_PIN T11 [get_ports {Display[5]}]
set_property PACKAGE_PIN P15 [get_ports {Display[4]}]
set_property PACKAGE_PIN K13 [get_ports {Display[3]}]
set_property PACKAGE_PIN K16 [get_ports {Display[2]}]
set_property PACKAGE_PIN R10 [get_ports {Display[1]}]
set_property PACKAGE_PIN T10 [get_ports {Display[0]}]